name: "pnpm-outdated-to-datadog"
description: "Github action to send metrics on outdated dependencies to datadog"
inputs:
  datadog-api-key:
    required: true
  github-token:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: pnpm/action-setup@v2
    - run: pnpm outdated --json
      shell: bash
      env:
        DATADOG_API_KEY: ${{ inputs.datadog-api-key }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
